version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: card-war-game-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "card_war_game"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - app_mysql_net

  app:
    image: card-war-game-app-img
    container_name: card-war-game-app
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - app_mysql_net

volumes:
  mysql_data:

networks:
  app_mysql_net:
    driver: bridge

